/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionIndexRouteImport } from './routes/auction/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as AuctionProfileRouteImport } from './routes/auction/profile'
import { Route as AuctionPlayersRouteImport } from './routes/auction/players'
import { Route as AuctionAuctionIdIndexRouteImport } from './routes/auction/$auctionId/index'
import { Route as AuctionAuctionIdFantasyRouteImport } from './routes/auction/$auctionId/fantasy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/auction/',
  path: '/auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/auth/__layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionProfileRoute = AuctionProfileRouteImport.update({
  id: '/auction/profile',
  path: '/auction/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionPlayersRoute = AuctionPlayersRouteImport.update({
  id: '/auction/players',
  path: '/auction/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdIndexRoute = AuctionAuctionIdIndexRouteImport.update({
  id: '/auction/$auctionId/',
  path: '/auction/$auctionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdFantasyRoute = AuctionAuctionIdFantasyRouteImport.update({
  id: '/auction/$auctionId/fantasy',
  path: '/auction/$auctionId/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction/players': typeof AuctionPlayersRoute
  '/auction/profile': typeof AuctionProfileRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auction/': typeof AuctionIndexRoute
  '/auction/$auctionId/fantasy': typeof AuctionAuctionIdFantasyRoute
  '/auction/$auctionId/': typeof AuctionAuctionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction/players': typeof AuctionPlayersRoute
  '/auction/profile': typeof AuctionProfileRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auction': typeof AuctionIndexRoute
  '/auction/$auctionId/fantasy': typeof AuctionAuctionIdFantasyRoute
  '/auction/$auctionId': typeof AuctionAuctionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auction/players': typeof AuctionPlayersRoute
  '/auction/profile': typeof AuctionProfileRoute
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auction/': typeof AuctionIndexRoute
  '/auction/$auctionId/fantasy': typeof AuctionAuctionIdFantasyRoute
  '/auction/$auctionId/': typeof AuctionAuctionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auction/players'
    | '/auction/profile'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auction/'
    | '/auction/$auctionId/fantasy'
    | '/auction/$auctionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auction/players'
    | '/auction/profile'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auction'
    | '/auction/$auctionId/fantasy'
    | '/auction/$auctionId'
  id:
    | '__root__'
    | '/'
    | '/auction/players'
    | '/auction/profile'
    | '/auth/__layout'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auction/'
    | '/auction/$auctionId/fantasy'
    | '/auction/$auctionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionPlayersRoute: typeof AuctionPlayersRoute
  AuctionProfileRoute: typeof AuctionProfileRoute
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  AuctionIndexRoute: typeof AuctionIndexRoute
  AuctionAuctionIdFantasyRoute: typeof AuctionAuctionIdFantasyRoute
  AuctionAuctionIdIndexRoute: typeof AuctionAuctionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/': {
      id: '/auction/'
      path: '/auction'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/profile': {
      id: '/auction/profile'
      path: '/auction/profile'
      fullPath: '/auction/profile'
      preLoaderRoute: typeof AuctionProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/players': {
      id: '/auction/players'
      path: '/auction/players'
      fullPath: '/auction/players'
      preLoaderRoute: typeof AuctionPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/': {
      id: '/auction/$auctionId/'
      path: '/auction/$auctionId'
      fullPath: '/auction/$auctionId/'
      preLoaderRoute: typeof AuctionAuctionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/fantasy': {
      id: '/auction/$auctionId/fantasy'
      path: '/auction/$auctionId/fantasy'
      fullPath: '/auction/$auctionId/fantasy'
      preLoaderRoute: typeof AuctionAuctionIdFantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionPlayersRoute: AuctionPlayersRoute,
  AuctionProfileRoute: AuctionProfileRoute,
  Auth_layoutRoute: Auth_layoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  AuctionIndexRoute: AuctionIndexRoute,
  AuctionAuctionIdFantasyRoute: AuctionAuctionIdFantasyRoute,
  AuctionAuctionIdIndexRoute: AuctionAuctionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
