/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionIndexRouteImport } from './routes/auction/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as AuctionProfileRouteImport } from './routes/auction/profile'
import { Route as AuctionPlayersRouteImport } from './routes/auction/players'
import { Route as AuctionAuctionIdIndexRouteImport } from './routes/auction/$auctionId/index'
import { Route as AuctionAuctionIdTradeRouteImport } from './routes/auction/$auctionId/trade'
import { Route as AuctionAuctionIdIplMatchesRouteImport } from './routes/auction/$auctionId/ipl-matches'
import { Route as AuctionAuctionIdFantasyRouteImport } from './routes/auction/$auctionId/fantasy'
import { Route as AuctionAuctionIdMidSeasonIndexRouteImport } from './routes/auction/$auctionId/mid-season/index'
import { Route as AuctionAuctionIdMidSeasonAdminRouteImport } from './routes/auction/$auctionId/mid-season/admin'
import { Route as AuctionAuctionIdFantasySquadIdRouteImport } from './routes/auction/$auctionId/fantasy/$squadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/auction/',
  path: '/auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/auth/__layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionProfileRoute = AuctionProfileRouteImport.update({
  id: '/auction/profile',
  path: '/auction/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionPlayersRoute = AuctionPlayersRouteImport.update({
  id: '/auction/players',
  path: '/auction/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdIndexRoute = AuctionAuctionIdIndexRouteImport.update({
  id: '/auction/$auctionId/',
  path: '/auction/$auctionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdTradeRoute = AuctionAuctionIdTradeRouteImport.update({
  id: '/auction/$auctionId/trade',
  path: '/auction/$auctionId/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdIplMatchesRoute =
  AuctionAuctionIdIplMatchesRouteImport.update({
    id: '/auction/$auctionId/ipl-matches',
    path: '/auction/$auctionId/ipl-matches',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuctionAuctionIdFantasyRoute = AuctionAuctionIdFantasyRouteImport.update({
  id: '/auction/$auctionId/fantasy',
  path: '/auction/$auctionId/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdMidSeasonIndexRoute =
  AuctionAuctionIdMidSeasonIndexRouteImport.update({
    id: '/auction/$auctionId/mid-season/',
    path: '/auction/$auctionId/mid-season/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuctionAuctionIdMidSeasonAdminRoute =
  AuctionAuctionIdMidSeasonAdminRouteImport.update({
    id: '/auction/$auctionId/mid-season/admin',
    path: '/auction/$auctionId/mid-season/admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuctionAuctionIdFantasySquadIdRoute =
  AuctionAuctionIdFantasySquadIdRouteImport.update({
    id: '/$squadId',
    path: '/$squadId',
    getParentRoute: () => AuctionAuctionIdFantasyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction/players': typeof AuctionPlayersRoute
  '/auction/profile': typeof AuctionProfileRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auction/': typeof AuctionIndexRoute
  '/auction/$auctionId/fantasy': typeof AuctionAuctionIdFantasyRouteWithChildren
  '/auction/$auctionId/ipl-matches': typeof AuctionAuctionIdIplMatchesRoute
  '/auction/$auctionId/trade': typeof AuctionAuctionIdTradeRoute
  '/auction/$auctionId/': typeof AuctionAuctionIdIndexRoute
  '/auction/$auctionId/fantasy/$squadId': typeof AuctionAuctionIdFantasySquadIdRoute
  '/auction/$auctionId/mid-season/admin': typeof AuctionAuctionIdMidSeasonAdminRoute
  '/auction/$auctionId/mid-season/': typeof AuctionAuctionIdMidSeasonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction/players': typeof AuctionPlayersRoute
  '/auction/profile': typeof AuctionProfileRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auction': typeof AuctionIndexRoute
  '/auction/$auctionId/fantasy': typeof AuctionAuctionIdFantasyRouteWithChildren
  '/auction/$auctionId/ipl-matches': typeof AuctionAuctionIdIplMatchesRoute
  '/auction/$auctionId/trade': typeof AuctionAuctionIdTradeRoute
  '/auction/$auctionId': typeof AuctionAuctionIdIndexRoute
  '/auction/$auctionId/fantasy/$squadId': typeof AuctionAuctionIdFantasySquadIdRoute
  '/auction/$auctionId/mid-season/admin': typeof AuctionAuctionIdMidSeasonAdminRoute
  '/auction/$auctionId/mid-season': typeof AuctionAuctionIdMidSeasonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auction/players': typeof AuctionPlayersRoute
  '/auction/profile': typeof AuctionProfileRoute
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auction/': typeof AuctionIndexRoute
  '/auction/$auctionId/fantasy': typeof AuctionAuctionIdFantasyRouteWithChildren
  '/auction/$auctionId/ipl-matches': typeof AuctionAuctionIdIplMatchesRoute
  '/auction/$auctionId/trade': typeof AuctionAuctionIdTradeRoute
  '/auction/$auctionId/': typeof AuctionAuctionIdIndexRoute
  '/auction/$auctionId/fantasy/$squadId': typeof AuctionAuctionIdFantasySquadIdRoute
  '/auction/$auctionId/mid-season/admin': typeof AuctionAuctionIdMidSeasonAdminRoute
  '/auction/$auctionId/mid-season/': typeof AuctionAuctionIdMidSeasonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auction/players'
    | '/auction/profile'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auction/'
    | '/auction/$auctionId/fantasy'
    | '/auction/$auctionId/ipl-matches'
    | '/auction/$auctionId/trade'
    | '/auction/$auctionId/'
    | '/auction/$auctionId/fantasy/$squadId'
    | '/auction/$auctionId/mid-season/admin'
    | '/auction/$auctionId/mid-season/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auction/players'
    | '/auction/profile'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auction'
    | '/auction/$auctionId/fantasy'
    | '/auction/$auctionId/ipl-matches'
    | '/auction/$auctionId/trade'
    | '/auction/$auctionId'
    | '/auction/$auctionId/fantasy/$squadId'
    | '/auction/$auctionId/mid-season/admin'
    | '/auction/$auctionId/mid-season'
  id:
    | '__root__'
    | '/'
    | '/auction/players'
    | '/auction/profile'
    | '/auth/__layout'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auction/'
    | '/auction/$auctionId/fantasy'
    | '/auction/$auctionId/ipl-matches'
    | '/auction/$auctionId/trade'
    | '/auction/$auctionId/'
    | '/auction/$auctionId/fantasy/$squadId'
    | '/auction/$auctionId/mid-season/admin'
    | '/auction/$auctionId/mid-season/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionPlayersRoute: typeof AuctionPlayersRoute
  AuctionProfileRoute: typeof AuctionProfileRoute
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  AuctionIndexRoute: typeof AuctionIndexRoute
  AuctionAuctionIdFantasyRoute: typeof AuctionAuctionIdFantasyRouteWithChildren
  AuctionAuctionIdIplMatchesRoute: typeof AuctionAuctionIdIplMatchesRoute
  AuctionAuctionIdTradeRoute: typeof AuctionAuctionIdTradeRoute
  AuctionAuctionIdIndexRoute: typeof AuctionAuctionIdIndexRoute
  AuctionAuctionIdMidSeasonAdminRoute: typeof AuctionAuctionIdMidSeasonAdminRoute
  AuctionAuctionIdMidSeasonIndexRoute: typeof AuctionAuctionIdMidSeasonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/': {
      id: '/auction/'
      path: '/auction'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/profile': {
      id: '/auction/profile'
      path: '/auction/profile'
      fullPath: '/auction/profile'
      preLoaderRoute: typeof AuctionProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/players': {
      id: '/auction/players'
      path: '/auction/players'
      fullPath: '/auction/players'
      preLoaderRoute: typeof AuctionPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/': {
      id: '/auction/$auctionId/'
      path: '/auction/$auctionId'
      fullPath: '/auction/$auctionId/'
      preLoaderRoute: typeof AuctionAuctionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/trade': {
      id: '/auction/$auctionId/trade'
      path: '/auction/$auctionId/trade'
      fullPath: '/auction/$auctionId/trade'
      preLoaderRoute: typeof AuctionAuctionIdTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/ipl-matches': {
      id: '/auction/$auctionId/ipl-matches'
      path: '/auction/$auctionId/ipl-matches'
      fullPath: '/auction/$auctionId/ipl-matches'
      preLoaderRoute: typeof AuctionAuctionIdIplMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/fantasy': {
      id: '/auction/$auctionId/fantasy'
      path: '/auction/$auctionId/fantasy'
      fullPath: '/auction/$auctionId/fantasy'
      preLoaderRoute: typeof AuctionAuctionIdFantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/mid-season/': {
      id: '/auction/$auctionId/mid-season/'
      path: '/auction/$auctionId/mid-season'
      fullPath: '/auction/$auctionId/mid-season/'
      preLoaderRoute: typeof AuctionAuctionIdMidSeasonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/mid-season/admin': {
      id: '/auction/$auctionId/mid-season/admin'
      path: '/auction/$auctionId/mid-season/admin'
      fullPath: '/auction/$auctionId/mid-season/admin'
      preLoaderRoute: typeof AuctionAuctionIdMidSeasonAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/fantasy/$squadId': {
      id: '/auction/$auctionId/fantasy/$squadId'
      path: '/$squadId'
      fullPath: '/auction/$auctionId/fantasy/$squadId'
      preLoaderRoute: typeof AuctionAuctionIdFantasySquadIdRouteImport
      parentRoute: typeof AuctionAuctionIdFantasyRoute
    }
  }
}

interface AuctionAuctionIdFantasyRouteChildren {
  AuctionAuctionIdFantasySquadIdRoute: typeof AuctionAuctionIdFantasySquadIdRoute
}

const AuctionAuctionIdFantasyRouteChildren: AuctionAuctionIdFantasyRouteChildren =
  {
    AuctionAuctionIdFantasySquadIdRoute: AuctionAuctionIdFantasySquadIdRoute,
  }

const AuctionAuctionIdFantasyRouteWithChildren =
  AuctionAuctionIdFantasyRoute._addFileChildren(
    AuctionAuctionIdFantasyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionPlayersRoute: AuctionPlayersRoute,
  AuctionProfileRoute: AuctionProfileRoute,
  Auth_layoutRoute: Auth_layoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  AuctionIndexRoute: AuctionIndexRoute,
  AuctionAuctionIdFantasyRoute: AuctionAuctionIdFantasyRouteWithChildren,
  AuctionAuctionIdIplMatchesRoute: AuctionAuctionIdIplMatchesRoute,
  AuctionAuctionIdTradeRoute: AuctionAuctionIdTradeRoute,
  AuctionAuctionIdIndexRoute: AuctionAuctionIdIndexRoute,
  AuctionAuctionIdMidSeasonAdminRoute: AuctionAuctionIdMidSeasonAdminRoute,
  AuctionAuctionIdMidSeasonIndexRoute: AuctionAuctionIdMidSeasonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
